on: [push]

env:
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'STAGING' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo ${{ github.ref }}
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: echo ${{ env.ENVIRONMENT }}
  deploy:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: echo ${{ env.ENVIRONMENT }}
