on:
  push:
    branches:
      - "*"
    tags:
      - "prod-*"

env:
  ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/prod') && 'PRODUCTION' || 'STAGING' }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo ${{ github.ref }}
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo $ENVIRONMENT
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/prod') }}
    steps:
      - name: Echo variables        
        run: |
          echo ${{ startsWith(github.ref, 'refs/tags/prod') }}
          echo "This is a production build"
          echo ${{ env.ENVIRONMENT }}
        env:
          STEP_SCOPED_ENVIRONMENT: ${{ env.ENVIRONMENT }}
