on:
  push:
    branches:
      - "*"
    tags:
      - "prod-*"

env:
  ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/prod') && 'PRODUCTION' || 'STAGING' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo ${{ github.ref }}
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      JOB_SCOPED_ENVIRONMENT: ${{ env.ENVIRONMENT }}
    steps:
      - name: Echo variables
        run: |
          echo $ENVIRONMENT
          echo "JOB_SCOPED_ENVIRONMENT: $JOB_SCOPED_ENVIRONMENT"
  deploy:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo "STEP_SCOPED_ENVIRONMENT: $STEP_SCOPED_ENVIRONMENT"
        env:
          STEP_SCOPED_ENVIRONMENT: ${{ env.ENVIRONMENT }}
