on:
  push:
    branches:
      - "*"
    tags:
      - "prod-*"

env:
  ENVIRONMENT: ${{ startsWith(github.ref, 'refs/tags/prod') && 'PRODUCTION' || 'STAGING' }}
  PRODUCTION_BUILD: ${{ startsWith(github.ref, 'refs/tags/prod') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.PRODUCTION_BUILD }}
          echo ${{ env.ENVIRONMENT }}
          echo ${{ github.ref }}
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables
        run: |
          echo $ENVIRONMENT
  deploy:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    if: ${{ env.PRODUCTION_BUILD == true }}
    steps:
      - name: Echo variables
        run: |
          echo ${{ env.PRODUCTION_BUILD }}
          echo "This is a production build"
          echo ${{ env.ENVIRONMENT }}
        env:
          STEP_SCOPED_ENVIRONMENT: ${{ env.ENVIRONMENT }}
